[project]
drom-version = "0.1"

[project]
authors = ["Fabrice LE FESSANT <fabrice.le_fessant@origin-labs.com>"]
ci-systems = ["ubuntu-latest", "macos-latest", "windows-latest"]
copyright = "OCamlPro & Origin Labs"
edition = "4.10.0"
github-organization = "ocamlpro"
license = "LGPL2"
min-edition = "4.10.0"
name = "ez_subst"
synopsis = "Ez_subst is a simple module to perform string substitutions"
version = "0.2.1"

# keys that you could also define:
# odoc-target = "...odoc-target..."
# sphinx-target = "...sphinx-target..."
# archive = "...archive..."
# dev-repo = "...dev-repo..."
# bug-reports = "...bug-reports..."
# doc-api = "...doc-api..."
# doc-gen = "...doc-gen..."
# homepage = "...homepage..."

[project]
description = """Ez_subst is a simple module to perform string substitutions, like
${brace}, $(paren), $[bracket] or $alpha. It provides many options
to configure the substitutions.
"""

[project]
skip = ["src/ez_subst/main.ml", "test/expect-tests/test.ml", "test/output-tests/dune", "test/output-tests/test1.expected"]

# project-wide library dependencies (not for package-specific deps)
[dependencies]

# project-wide tools dependencies (not for package-specific deps)
[tools.ocamlformat]
for-test = true
[tools.odoc]
for-doc = true
[tools.ppx_expect]
for-test = true
[tools.ppx_inline_test]
for-test = true

[project]

# dirs to skip while scanning for dune files
skip-dirs = []

# dirs to scan for share/ folders (with package names)
share-dirs = ["share"]

# build profile to use by default
# build-profile = ...

# Profile options for this project
#    [profile]
#    dev = { ocaml-flags = "-w +a-4-40-41-42-44" }
#    release = { ocaml-flags = "-w -a" }
[profile]
# ...

# project-wide fields (depends on project skeleton)
[fields]
# ...

[[package]]
dir = "src/ez_subst"
# edit 'src/ez_subst/package.toml' for package-specific options

[[package]]
dir = "src/ez_subst_program"
# edit 'src/ocp-subst/package.toml' for package-specific options

